name: Build Packages and Update Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  Build-and-Update-Release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 18     
          
      - name: Install Dependencies for SvelteKit-App
        run: |
          cd ./Sveltekit-App
          npm install
          
      - name: Install Dependencies for Electron-App
        run: |
          cd ./Electron-App
          npm install
      
      - name: Build SvelteKit
        run: |
          cd ./Sveltekit-App
          npm run build
          
      - name: Build Electron
        run: |
          cd ./Electron-App
          npm run publish --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
