name: Build and Update Release

on:
    push:
        branches:
            - main
jobs:
    Build-and-Release:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: 0
            - uses: actions/setup-node@master
              with:
                  node-version: 18

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

            - name: Create Draft Release
              uses: softprops/action-gh-release@v1
              with:
                  draft: true
                  prerelease: true
                  tag_name: v${{ steps.package-version.outputs.current-version  }}
                  release_name: v${{ steps.package-version.outputs.current-version  }}

            - name: Install deps
              run: npm install

            - name: publish
              run: |
                  npm run build
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
