name: Build Packages and Update Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Build-and-Update-Release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache SvelteKit Dependencies
        uses: actions/cache@v2
        with:
          path: ./Sveltekit-App/node_modules
          key: ${{ matrix.os }}-sveltekit-${{ hashFiles('**/Sveltekit-App/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-sveltekit-

      - name: Cache Electron Dependencies
        uses: actions/cache@v2
        with:
          path: ./Electron-App/node_modules
          key: ${{ matrix.os }}-electron-${{ hashFiles('**/Electron-App/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-electron-

      - name: Install Dependencies
        run: |
          npm --prefix ./Sveltekit-App install ./Sveltekit-App
          npm --prefix ./Electron-App install ./Electron-App

      - name: Build SvelteKit
        run: |
          npm --prefix ./Sveltekit-App run build

      - name: Build Electron
        run: |
          npm --prefix ./Electron-App run publish --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
