name: Build and Update Release

on:
    push:
        branches:
            - main
jobs:
    Build-and-Update-Release:
        runs-on: linux-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}
                  fetch-depth: 0
            - uses: actions/setup-node@master
              with:
                  node-version: 18

            - name: Get Version
              id: get-version
              uses: beaconbrigade/package-json-version@v0.3
              with:
                  path: .

            - name: Create Draft Release
              uses: softprops/action-gh-release@v1
              with:
                  draft: true
                  prerelease: true
                  tag_name: v${{ steps.get-version.outputs.version  }}

            - name: Install deps
              run: npm install

            - name: publish
              run: |
                  npm run build
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
